### ISSUE TITLE
Unable to use Add REST API client

### ISSUE THREAD

**Issue by weitzhandler** [Azure-Samples/app-service-api-dotnet-todo-list#7]
After reading [this](https://docs.microsoft.com/en-us/azure/app-service-api/app-service-api-dotnet-get-started#a-idcodegena-generate-client-code-for-the-data-tier) page, when trying to use this option to Xamarin portable app client (from a swagger json file), I get the following message:

> Generating client code and adding to project started
> Generate client code for REST API with following parameters:
> REST API Name: MyProject API info, Base namespace: MyProject.App, Metadata file path: C:\Users\weitz\OneDrive\Documents\Visual Studio 2015\Projects\MyProject\src\MyProject\swagger.json
> Exception: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
> Generating client code and adding to project failed
> Adding REST API client for failed

Steps to reproduce:

- Create VS 2015 ASP.NET Core API app and add swagger with its UI and configure it
- Run the app and save the _swagger.json_ file (link appears on the header)
- Add a portable Xamarin or Prism project
- Add `Newtonsoft.Json` package via nuget
- Right click the client project -> Add -> REST API client
- Choose _Select an existing Swagger metadata file_ and browse to the saved file
- The following error shows up (text copied above):
![](http://i.imgur.com/XYrA5zV.png)

**Comment by wondering639** [comment]
Solution can meanwhile be found in the comments of https://docs.microsoft.com/en-us/azure/app-service-api/app-service-api-dotnet-get-started:

> Jabele 1 day ago
> @mshetty27 @ashwin Add the Newtonsoft.Json.dll (7.0.1 version) to the C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE folder. Re-run Add Rest Client command.

**Comment by weitzhandler** [comment]
@wondering639 
That's exactly the tutorial I followed in order to get the error I reported.

**Comment by weitzhandler** [comment]
That solved the problem.
Thanks a lot @wondering639.
Anyway, looks like the generator isn't sufficient enough, my consumer is a XAML project and thus I need generated INPC entities.

I wonder why there is no reliable in-project page for coordinating WebApi generation into neighboring projects in solution, the generation should be independent to swagger I think, there should just be a way to marry a client and a WebApi having the client entities generated (with some customizable options, maybe T4) in the client.
[Here](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/17996317-it-s-about-time-for-a-restful-client-generator)'s my suggestion on UserVoice, **please vote** and share your thoughts.
